name: Batchsplitter-Build.yml
run-name: Batchsplitter-${{ inputs.Build }}Build-${{ github.run_number }}

on:
  workflow_dispatch:
    inputs:
      Branch: 
        description: 'Enter the Branch to Build'
        required: true
        default: 'main'
      Build:
        description: 'Select The Build Type to Trigger'
        required: true
        default: Dev
        type: choice
        options:
          - Dev
          - Rel

jobs:
  build-job:
    runs-on: ubuntu-latest
    env:
      Build_Number: ${{ github.run_number }}
      Branch_Name: ${{ github.event.inputs.Branch }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.Branch }}

      # Additional steps for your build process
      # e.g., setting up Java, building the project, etc.

      - name: Set Build Number
        run: echo "Build_Number=${{ github.run_number }}" >> $GITHUB_ENV

  call-reusable-workflow:
    needs: build-job
    uses: PrabhuTR/Reuseable-actions/.github/workflows/Send%20Teams%20Notification.yml@main
    with:
      version_number: ${{ needs.build-job.outputs.Build_Number }}
      branch: ${{ github.event.inputs.Branch }}
