name: Batchsplitter-Build.yml
run-name: Batchsplitter-${{ inputs.Build }}Build-${{ github.run_number }}

on:
  workflow_dispatch:
    inputs:
      Branch: 
        description: 'Enter the Branch to Build'
        required: true
        default: 'main'
      Build:
        description: 'Select The Build Type to Trigger'
        required: true
        default: Dev
        type: choice
        options:
          - Dev
          - Rel

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.Branch }}

      # Other steps as necessary

  call-reusable-workflow:
    uses: PrabhuTR/Reuseable-actions/.github/workflows/send-teams-notification.yml@main
    with:
      version_number: ${{ env.Build_Number }}
      branch: ${{ github.event.inputs.Branch }}
